// These styles apply to every route in the application
import "./globals.css";
import { Montserrat } from "next/font/google";
import React from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const font = Montserrat({
	subsets: ["latin"],
	weight: ["500"],
});

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={font.className}>
			<body className="h-full bg-cover bg-slate-100 ">
				<SpeedInsights></SpeedInsights>
				{children}
			</body>
		</html>
	);
}
